include(ExternalProject)

ExternalProject_Add(cwalk
	DOWNLOAD_COMMAND URL https://github.com/likle/cwalk/archive/refs/tags/v1.2.9.tar.gz
  DOWNLOAD_COMMAND URL_HASH SHA256=54f160031687ec90a414e0656cf6266445207cb91b720dacf7a7c415d6bc7108
  DOWNLOAD_COMMAND DOWNLOAD_EXTRACT_TIMESTAMP true
  CMAKE_ARGS
             -DCMAKE_VERBOSE_MAKEFILE=ON
             -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>/install
             -DBUILD_TESTING=OFF
             -DBUILD_SHARED_LIBS=OFF
             -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
             -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
             -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=OFF
             -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  BUILD_IN_SOURCE 0
  INSTALL_COMMAND ${INST_ARGS} ${CMAKE_COMMAND} --install <BINARY_DIR>
)
